export enum WebhookPlaidType {
  TRANSACTIONS = 'TRANSACTIONS',
  ITEM = 'ITEM',
}

export enum WebhookPlaidCode {
  //  Transactions
  TRANSACTIONS_REMOVED = 'TRANSACTIONS_REMOVED',
  DEFAULT_UPDATE = 'DEFAULT_UPDATE',
  HISTORICAL_UPDATE = 'HISTORICAL_UPDATE',
  INITIAL_UPDATE = 'INITIAL_UPDATE',

  //  Item Events
  ITEM_REMOVE = 'ITEM_REMOVE',
  ITEM_LOGIN_REQUIRED = 'ITEM_LOGIN_REQUIRED',
  USER_PERMISSION_REVOKED = 'USER_PERMISSION_REVOKED',
  USER_ACCOUNT_REVOKED = 'USER_ACCOUNT_REVOKED',
  WEBHOOK_UPDATE_ACKNOWLEDGED = 'WEBHOOK_UPDATE_ACKNOWLEDGED',
}
