export enum PlaidLanguageCodeEnum {
  DANISH = 'da',
  DUTCH = 'nl',
  ENGLISH = 'en',
  ESTONIAN = 'et',
  FRENCH = 'fr',
  GERMAN = 'de',
  HINDI = 'hi',
  ITALIAN = 'it',
  LATVIAN = 'lv',
  LITHUANIAN = 'lt',
  NORWEGIAN = 'no',
  POLISH = 'pl',
  PORTUGUESE = 'pt',
  ROMANIAN = 'ro',
  SPANISH = 'es',
  SWEDISH = 'sv',
  VIETNAMESE = 'vi',
}

export enum PlaidCountryCodeEnum {
  US = 'US',
  GB = 'GB',
  ES = 'ES',
  NL = 'NL',
  FR = 'FR',
  IE = 'IE',
  CA = 'CA',
  DE = 'DE',
  IT = 'IT',
  PL = 'PL',
  DK = 'DK',
  NO = 'NO',
  SE = 'SE',
  EE = 'EE',
  LT = 'LT',
  LV = 'LV',
  PT = 'PT',
  BE = 'BE',
}
